let drinks = [
    {
        idDrink: '15997',
        strDrink: 'GG',
        strDrinkAlternate: null,
        strTags: null,
        strVideo: null,
        strCategory: 'Ordinary Drink',
        strIBA: null,
        strAlcoholic: 'Optional alcohol',
        strGlass: 'Collins Glass',
        strInstructions:
            'Pour the Galliano liqueur over ice. Fill the remainder of the glass with ginger ale and thats all there is to it. You now have a your very own GG.',
        strInstructionsES: null,
        strInstructionsDE:
            'Den Galliano-Likör über Eis gießen. Füllen Sie den Rest des Glases mit Ginger Ale und das ist alles, was dazu gehört. Du hast jetzt ein eigenes GG.',
        strInstructionsFR: null,
        strInstructionsIT:
            'Versare il liquore Galliano su ghiaccio.Riempi il resto del bicchiere con ginger ale e questo è tutto.Ora hai il tuo GG personale.',
        strInstructionsZHHANS: null,
        strInstructionsZHHANT: null,
        strDrinkThumb:
            'https://www.thecocktaildb.com/images/media/drink/vyxwut1468875960.jpg',
        strIngredient: 'Galliano',
        strIngredient: 'Ginger ale',
        strIngredient: 'Ice',
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient0: null,
        strIngredient1: null,
        strIngredient2: null,
        strIngredient3: null,
        strIngredient4: null,
        strIngredient5: null,
        strMeasure: '2 1/2 shots ',
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure0: null,
        strMeasure1: null,
        strMeasure2: null,
        strMeasure3: null,
        strMeasure4: null,
        strMeasure5: null,
        strImageSource: null,
        strImageAttribution: null,
        strCreativeCommonsConfirmed: 'No',
        dateModified: '2016-07-18 22:06:00',
    },
    {
        idDrink: '17222',
        strDrink: 'A1',
        strDrinkAlternate: null,
        strTags: null,
        strVideo: null,
        strCategory: 'Cocktail',
        strIBA: null,
        strAlcoholic: 'Alcoholic',
        strGlass: 'Cocktail glass',
        strInstructions:
            'Pour all ingredients into a cocktail shaker, mix and serve over ice into a chilled glass.',
        strInstructionsES: null,
        strInstructionsDE:
            'Alle Zutaten in einen Cocktailshaker geben, mischen und über Eis in ein gekühltes Glas servieren.',
        strInstructionsFR: null,
        strInstructionsIT:
            'Versare tutti gli ingredienti in uno shaker, mescolare e servire con ghiaccio in un bicchiere freddo.',
        strInstructionsZHHANS: null,
        strInstructionsZHHANT: null,
        strDrinkThumb:
            'https://www.thecocktaildb.com/images/media/drink/2x8thr1504816928.jpg',
        strIngredient: 'Gin',
        strIngredient: 'Grand Marnier',
        strIngredient: 'Lemon Juice',
        strIngredient: 'Grenadine',
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient0: null,
        strIngredient1: null,
        strIngredient2: null,
        strIngredient3: null,
        strIngredient4: null,
        strIngredient5: null,
        strMeasure: '1 3/4 shot ',
        strMeasure: '1 Shot ',
        strMeasure: '1/4 Shot',
        strMeasure: '1/8 Shot',
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure0: null,
        strMeasure1: null,
        strMeasure2: null,
        strMeasure3: null,
        strMeasure4: null,
        strMeasure5: null,
        strImageSource: null,
        strImageAttribution: null,
        strCreativeCommonsConfirmed: 'No',
        dateModified: '2017-09-07 21:42:09',
    },
    {
        idDrink: '13501',
        strDrink: 'ABC',
        strDrinkAlternate: null,
        strTags: null,
        strVideo: null,
        strCategory: 'Shot',
        strIBA: null,
        strAlcoholic: 'Alcoholic',
        strGlass: 'Shot glass',
        strInstructions: 'Layered in a shot glass.',
        strInstructionsES: null,
        strInstructionsDE: 'Schichtaufbau in einem Schnapsglas.',
        strInstructionsFR: null,
        strInstructionsIT:
            "Versa in ordine di lettera i vari ingredienti. 1/3 del bicchiere va riempito con l'Amaretto, 1/3 di Baileys e il restante di Cognac.",
        strInstructionsZHHANS: null,
        strInstructionsZHHANT: null,
        strDrinkThumb:
            'https://www.thecocktaildb.com/images/media/drink/tqpvqp1472668328.jpg',
        strIngredient: 'Amaretto',
        strIngredient: 'Baileys irish cream',
        strIngredient: 'Cognac',
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient0: null,
        strIngredient1: null,
        strIngredient2: null,
        strIngredient3: null,
        strIngredient4: null,
        strIngredient5: null,
        strMeasure: '1/3 ',
        strMeasure: '1/3 ',
        strMeasure: '1/3 ',
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure0: null,
        strMeasure1: null,
        strMeasure2: null,
        strMeasure3: null,
        strMeasure4: null,
        strMeasure5: null,
        strImageSource: null,
        strImageAttribution: null,
        strCreativeCommonsConfirmed: 'No',
        dateModified: '2016-08-31 19:32:08',
    },
    {
        idDrink: '17203',
        strDrink: 'Kir',
        strDrinkAlternate: null,
        strTags: 'IBA,ContemporaryClassic',
        strVideo: null,
        strCategory: 'Ordinary Drink',
        strIBA: null,
        strAlcoholic: 'Alcoholic',
        strGlass: 'Wine Glass',
        strInstructions:
            'Add the crème de cassis to the bottom of the glass, then top up with wine.',
        strInstructionsES: null,
        strInstructionsDE:
            'Gib die Creme de Cassis auf den Boden des Glases und füge dann Wein hinzu.',
        strInstructionsFR: null,
        strInstructionsIT:
            'Aggiungere la crème de cassis sul fondo del bicchiere, quindi rabboccare con il vino.',
        strInstructionsZHHANS: null,
        strInstructionsZHHANT: null,
        strDrinkThumb:
            'https://www.thecocktaildb.com/images/media/drink/apneom1504370294.jpg',
        strIngredient: 'Creme de Cassis',
        strIngredient: 'Champagne',
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient0: null,
        strIngredient1: null,
        strIngredient2: null,
        strIngredient3: null,
        strIngredient4: null,
        strIngredient5: null,
        strMeasure: '1 part ',
        strMeasure: '5 parts ',
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure0: null,
        strMeasure1: null,
        strMeasure2: null,
        strMeasure3: null,
        strMeasure4: null,
        strMeasure5: null,
        strImageSource: null,
        strImageAttribution: null,
        strCreativeCommonsConfirmed: 'No',
        dateModified: '2017-09-02 17:38:14',
    },
    {
        idDrink: '14229',
        strDrink: '747',
        strDrinkAlternate: null,
        strTags: null,
        strVideo: null,
        strCategory: 'Shot',
        strIBA: null,
        strAlcoholic: 'Alcoholic',
        strGlass: 'Shot glass',
        strInstructions:
            'pour kaluha, then Baileys, then Frangelico not chilled and not layered -- SERVE!!!',
        strInstructionsES: null,
        strInstructionsDE:
            'Gießen Sie kaluha, dann Baileys, dann Frangelico nicht gekühlt und nicht geschichtet -- SERVE!!!!!!!!',
        strInstructionsFR: null,
        strInstructionsIT: 'Versa Kahlua, Baileys e poi Frangelico.',
        strInstructionsZHHANS: null,
        strInstructionsZHHANT: null,
        strDrinkThumb:
            'https://www.thecocktaildb.com/images/media/drink/xxsxqy1472668106.jpg',
        strIngredient: 'Kahlua',
        strIngredient: 'Baileys irish cream',
        strIngredient: 'Frangelico',
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient0: null,
        strIngredient1: null,
        strIngredient2: null,
        strIngredient3: null,
        strIngredient4: null,
        strIngredient5: null,
        strMeasure: '1/3 part ',
        strMeasure: '1/3 part ',
        strMeasure: '1/3 part ',
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure0: null,
        strMeasure1: null,
        strMeasure2: null,
        strMeasure3: null,
        strMeasure4: null,
        strMeasure5: null,
        strImageSource: null,
        strImageAttribution: null,
        strCreativeCommonsConfirmed: 'No',
        dateModified: '2016-08-31 19:28:26',
    },
    {
        idDrink: '15288',
        strDrink: '252',
        strDrinkAlternate: null,
        strTags: null,
        strVideo: null,
        strCategory: 'Shot',
        strIBA: null,
        strAlcoholic: 'Alcoholic',
        strGlass: 'Shot glass',
        strInstructions:
            'Add both ingredients to shot glass, shoot, and get drunk quick',
        strInstructionsES: null,
        strInstructionsDE: 'Beide Zutaten in ein Schnapsglas geben.',
        strInstructionsFR: null,
        strInstructionsIT:
            'Aggiungi entrambi gli ingredienti al bicchierino, bevi e ubriacati velocemente',
        strInstructionsZHHANS: null,
        strInstructionsZHHANT: null,
        strDrinkThumb:
            'https://www.thecocktaildb.com/images/media/drink/rtpxqw1468877562.jpg',
        strIngredient: '151 proof rum',
        strIngredient: 'Wild Turkey',
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient0: null,
        strIngredient1: null,
        strIngredient2: null,
        strIngredient3: null,
        strIngredient4: null,
        strIngredient5: null,
        strMeasure: '1/2 shot Bacardi ',
        strMeasure: '1/2 shot ',
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure0: null,
        strMeasure1: null,
        strMeasure2: null,
        strMeasure3: null,
        strMeasure4: null,
        strMeasure5: null,
        strImageSource: null,
        strImageAttribution: null,
        strCreativeCommonsConfirmed: 'No',
        dateModified: '2016-07-18 22:32:42',
    },
    {
        idDrink: '17225',
        strDrink: 'Ace',
        strDrinkAlternate: null,
        strTags: null,
        strVideo: null,
        strCategory: 'Cocktail',
        strIBA: null,
        strAlcoholic: 'Alcoholic',
        strGlass: 'Martini Glass',
        strInstructions:
            'Shake all the ingredients in a cocktail shaker and ice then strain in a cold glass.',
        strInstructionsES: null,
        strInstructionsDE:
            'Alle Zutaten in einem Cocktailshaker mit Eis schütteln und dann in einem kalten Glas abseihen.',
        strInstructionsFR: null,
        strInstructionsIT:
            'Shakerare tutti gli ingredienti in uno shaker e ghiaccio, quindi filtrare in un bicchiere freddo.',
        strInstructionsZHHANS: null,
        strInstructionsZHHANT: null,
        strDrinkThumb:
            'https://www.thecocktaildb.com/images/media/drink/l3cd7f1504818306.jpg',
        strIngredient: 'Gin',
        strIngredient: 'Grenadine',
        strIngredient: 'Heavy cream',
        strIngredient: 'Milk',
        strIngredient: 'Egg White',
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient0: null,
        strIngredient1: null,
        strIngredient2: null,
        strIngredient3: null,
        strIngredient4: null,
        strIngredient5: null,
        strMeasure: '2 shots ',
        strMeasure: '1/2 shot ',
        strMeasure: '1/2 shot ',
        strMeasure: '1/2 shot',
        strMeasure: '1/2 Fresh',
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure0: null,
        strMeasure1: null,
        strMeasure2: null,
        strMeasure3: null,
        strMeasure4: null,
        strMeasure5: null,
        strImageSource: null,
        strImageAttribution: null,
        strCreativeCommonsConfirmed: 'No',
        dateModified: '2017-09-07 22:05:06',
    },
    {
        idDrink: '17837',
        strDrink: 'Adam',
        strDrinkAlternate: null,
        strTags: 'Alcoholic,Holiday',
        strVideo: null,
        strCategory: 'Ordinary Drink',
        strIBA: null,
        strAlcoholic: 'Alcoholic',
        strGlass: 'Cocktail glass',
        strInstructions:
            'In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a cocktail glass.',
        strInstructionsES: null,
        strInstructionsDE:
            'In einem Shaker, der halb mit Eiswürfeln gefüllt ist, alle Zutaten vermengen. Gut schütteln. In ein Cocktailglas abseihen.',
        strInstructionsFR: null,
        strInstructionsIT:
            'In uno shaker riempito a metà con cubetti di ghiaccio, unire tutti gli ingredienti.Agitare bene.Filtrare in un bicchiere da cocktail.',
        strInstructionsZHHANS: null,
        strInstructionsZHHANT: null,
        strDrinkThumb:
            'https://www.thecocktaildb.com/images/media/drink/v0at4i1582478473.jpg',
        strIngredient: 'Dark rum',
        strIngredient: 'Lemon juice',
        strIngredient: 'Grenadine',
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient0: null,
        strIngredient1: null,
        strIngredient2: null,
        strIngredient3: null,
        strIngredient4: null,
        strIngredient5: null,
        strMeasure: '2 oz ',
        strMeasure: '1 oz ',
        strMeasure: '1 tsp ',
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure0: null,
        strMeasure1: null,
        strMeasure2: null,
        strMeasure3: null,
        strMeasure4: null,
        strMeasure5: null,
        strImageSource: null,
        strImageAttribution: null,
        strCreativeCommonsConfirmed: 'Yes',
        dateModified: '2016-09-02 11:29:29',
    },
    {
        idDrink: '13332',
        strDrink: 'B-53',
        strDrinkAlternate: null,
        strTags: null,
        strVideo: null,
        strCategory: 'Shot',
        strIBA: null,
        strAlcoholic: 'Alcoholic',
        strGlass: 'Collins Glass',
        strInstructions:
            'Layer the Kahlua, Sambucca and Grand Marnier into a shot glas in that order. Better than B-52',
        strInstructionsES: null,
        strInstructionsDE:
            'Schichte die Kahlua, Sambucca und Grand Marnier in dieser Reihenfolge in ein Schnapsglas ein. Besser als B-52',
        strInstructionsFR: null,
        strInstructionsIT:
            "Metti Kahlua, Sambuca e Grand Marnier in un bicchierino in quest'ordine. ",
        strInstructionsZHHANS: null,
        strInstructionsZHHANT: null,
        strDrinkThumb:
            'https://www.thecocktaildb.com/images/media/drink/rwqxrv1461866023.jpg',
        strIngredient: 'Kahlua',
        strIngredient: 'Sambuca',
        strIngredient: 'Grand Marnier',
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient0: null,
        strIngredient1: null,
        strIngredient2: null,
        strIngredient3: null,
        strIngredient4: null,
        strIngredient5: null,
        strMeasure: '1/3 shot ',
        strMeasure: '1/3 shot ',
        strMeasure: '1/3 shot ',
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure0: null,
        strMeasure1: null,
        strMeasure2: null,
        strMeasure3: null,
        strMeasure4: null,
        strMeasure5: null,
        strImageSource: null,
        strImageAttribution: null,
        strCreativeCommonsConfirmed: 'No',
        dateModified: '2016-04-28 18:53:43',
    },
    {
        idDrink: '13938',
        strDrink: 'AT&amp;T',
        strDrinkAlternate: null,
        strTags: null,
        strVideo: null,
        strCategory: 'Ordinary Drink',
        strIBA: null,
        strAlcoholic: 'Alcoholic',
        strGlass: 'Highball Glass',
        strInstructions: 'Pour Vodka and Gin over ice, add Tonic and Stir',
        strInstructionsES: null,
        strInstructionsDE:
            'Wodka und Gin über das Eis gießen, Tonic hinzufügen und umrühren.',
        strInstructionsFR: null,
        strInstructionsIT:
            "Versare la vodka e il gin sul ghiaccio, aggiungere l'acqua tonica e mescolare",
        strInstructionsZHHANS: null,
        strInstructionsZHHANT: null,
        strDrinkThumb:
            'https://www.thecocktaildb.com/images/media/drink/rhhwmp1493067619.jpg',
        strIngredient: 'Absolut Vodka',
        strIngredient: 'Gin',
        strIngredient: 'Tonic water',
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient0: null,
        strIngredient1: null,
        strIngredient2: null,
        strIngredient3: null,
        strIngredient4: null,
        strIngredient5: null,
        strMeasure: '1 oz ',
        strMeasure: '1 oz ',
        strMeasure: '4 oz ',
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure0: null,
        strMeasure1: null,
        strMeasure2: null,
        strMeasure3: null,
        strMeasure4: null,
        strMeasure5: null,
        strImageSource: null,
        strImageAttribution: null,
        strCreativeCommonsConfirmed: 'No',
        dateModified: '2017-04-24 22:00:19',
    },
    {
        idDrink: '14610',
        strDrink: 'ACID',
        strDrinkAlternate: null,
        strTags: null,
        strVideo: null,
        strCategory: 'Shot',
        strIBA: null,
        strAlcoholic: 'Alcoholic',
        strGlass: 'Shot glass',
        strInstructions:
            'Poor in the 151 first followed by the 101 served with a Coke or Dr Pepper chaser.',
        strInstructionsES: null,
        strInstructionsDE:
            'Gering den 151 gefolgt von der 101, die mit einer Cola oder Dr. Pepper Chaser serviert wird.',
        strInstructionsFR: null,
        strInstructionsIT:
            'Versa prima il Bacardi 151 seguito dal 101, servito con una Coca-Cola.',
        strInstructionsZHHANS: null,
        strInstructionsZHHANT: null,
        strDrinkThumb:
            'https://www.thecocktaildb.com/images/media/drink/xuxpxt1479209317.jpg',
        strIngredient: '151 proof rum',
        strIngredient: 'Wild Turkey',
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient0: null,
        strIngredient1: null,
        strIngredient2: null,
        strIngredient3: null,
        strIngredient4: null,
        strIngredient5: null,
        strMeasure: '1 oz Bacardi ',
        strMeasure: '1 oz ',
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure0: null,
        strMeasure1: null,
        strMeasure2: null,
        strMeasure3: null,
        strMeasure4: null,
        strMeasure5: null,
        strImageSource: null,
        strImageAttribution: null,
        strCreativeCommonsConfirmed: 'No',
        dateModified: '2016-11-15 11:28:37',
    },
    {
        idDrink: '15853',
        strDrink: 'B-52',
        strDrinkAlternate: null,
        strTags: 'IBA,NewEra',
        strVideo: null,
        strCategory: 'Shot',
        strIBA: 'New Era Drinks',
        strAlcoholic: 'Alcoholic',
        strGlass: 'Shot glass',
        strInstructions:
            'Layer ingredients into a shot glass. Serve with a stirrer.',
        strInstructionsES: null,
        strInstructionsDE:
            'Zutaten in ein Schnapsglas schichten. Mit einem Rührstab servieren.',
        strInstructionsFR: null,
        strInstructionsIT:
            'Metti gli ingredienti in un bicchiere da shot a strati.Servire con una paletta.',
        strInstructionsZHHANS: null,
        strInstructionsZHHANT: null,
        strDrinkThumb:
            'https://www.thecocktaildb.com/images/media/drink/5a3vg61504372070.jpg',
        strIngredient: 'Baileys irish cream',
        strIngredient: 'Grand Marnier',
        strIngredient: 'Kahlua',
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient0: null,
        strIngredient1: null,
        strIngredient2: null,
        strIngredient3: null,
        strIngredient4: null,
        strIngredient5: null,
        strMeasure: '1/3 ',
        strMeasure: '1/3 ',
        strMeasure: '1/4 ',
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure0: null,
        strMeasure1: null,
        strMeasure2: null,
        strMeasure3: null,
        strMeasure4: null,
        strMeasure5: null,
        strImageSource: null,
        strImageAttribution: null,
        strCreativeCommonsConfirmed: 'No',
        dateModified: '2017-09-02 18:07:51',
    },
    {
        idDrink: '16262',
        strDrink: 'H.D.',
        strDrinkAlternate: null,
        strTags: null,
        strVideo: null,
        strCategory: 'Coffee / Tea',
        strIBA: null,
        strAlcoholic: 'Alcoholic',
        strGlass: 'Beer mug',
        strInstructions:
            'Mix the whisky and Baileys Cream in a beer-glass (at least 50 cl). Fill the rest of the glass with coffee.',
        strInstructionsES: null,
        strInstructionsDE:
            'Den Whisky und die Baileys Cream in einem Bierglas (mind. 50 cl) mischen. Füllen Sie den Rest des Glases mit Kaffee.',
        strInstructionsFR: null,
        strInstructionsIT:
            'Mescolare il whisky e la crema di Baileys in un bicchiere da birra (almeno 50 cl).Riempi il resto del bicchiere di caffè.',
        strInstructionsZHHANS: null,
        strInstructionsZHHANT: null,
        strDrinkThumb:
            'https://www.thecocktaildb.com/images/media/drink/upusyu1472667977.jpg',
        strIngredient: 'Whisky',
        strIngredient: 'Baileys irish cream',
        strIngredient: 'Coffee',
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient0: null,
        strIngredient1: null,
        strIngredient2: null,
        strIngredient3: null,
        strIngredient4: null,
        strIngredient5: null,
        strMeasure: '4 cl ',
        strMeasure: '8 cl ',
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure0: null,
        strMeasure1: null,
        strMeasure2: null,
        strMeasure3: null,
        strMeasure4: null,
        strMeasure5: null,
        strImageSource: null,
        strImageAttribution: null,
        strCreativeCommonsConfirmed: 'No',
        dateModified: '2016-08-31 19:26:18',
    },
    {
        idDrink: '17141',
        strDrink: 'Smut',
        strDrinkAlternate: null,
        strTags: null,
        strVideo: null,
        strCategory: 'Punch / Party Drink',
        strIBA: null,
        strAlcoholic: 'Alcoholic',
        strGlass: 'Beer mug',
        strInstructions: 'Throw it all together and serve real cold.',
        strInstructionsES: null,
        strInstructionsDE: 'Schütte alles zusammen und serviere es kalt.',
        strInstructionsFR: null,
        strInstructionsIT: 'Metti tutto insieme e servi freddo.',
        strInstructionsZHHANS: null,
        strInstructionsZHHANT: null,
        strDrinkThumb:
            'https://www.thecocktaildb.com/images/media/drink/rx8k8e1504365812.jpg',
        strIngredient: 'Red wine',
        strIngredient: 'Peach schnapps',
        strIngredient: 'Pepsi Cola',
        strIngredient: 'Orange juice',
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient0: null,
        strIngredient1: null,
        strIngredient2: null,
        strIngredient3: null,
        strIngredient4: null,
        strIngredient5: null,
        strMeasure: '1/3 part ',
        strMeasure: '1 shot ',
        strMeasure: '1/3 part ',
        strMeasure: '1/3 part ',
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure0: null,
        strMeasure1: null,
        strMeasure2: null,
        strMeasure3: null,
        strMeasure4: null,
        strMeasure5: null,
        strImageSource: null,
        strImageAttribution: null,
        strCreativeCommonsConfirmed: 'No',
        dateModified: '2017-09-02 16:23:32',
    },
    {
        idDrink: '17208',
        strDrink: 'Rose',
        strDrinkAlternate: null,
        strTags: 'IBA,ContemporaryClassic',
        strVideo: null,
        strCategory: 'Ordinary Drink',
        strIBA: 'Contemporary Classics',
        strAlcoholic: 'Alcoholic',
        strGlass: 'Cocktail glass',
        strInstructions:
            'Shake together in a cocktail shaker, then strain into chilled glass. Garnish and serve.',
        strInstructionsES: null,
        strInstructionsDE:
            'In einem Cocktailshaker vermengen und dann in ein gekühltes Glas abseihen. Garnieren und servieren.',
        strInstructionsFR: null,
        strInstructionsIT:
            'Shakerare insieme in uno shaker, quindi filtrare in un bicchiere freddo.Guarnire e servire.',
        strInstructionsZHHANS: null,
        strInstructionsZHHANT: null,
        strDrinkThumb:
            'https://www.thecocktaildb.com/images/media/drink/8kxbvq1504371462.jpg',
        strIngredient: 'Dry Vermouth',
        strIngredient: 'Gin',
        strIngredient: 'Apricot brandy',
        strIngredient: 'Lemon juice',
        strIngredient: 'Grenadine',
        strIngredient: 'Powdered sugar',
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient0: null,
        strIngredient1: null,
        strIngredient2: null,
        strIngredient3: null,
        strIngredient4: null,
        strIngredient5: null,
        strMeasure: '1/2 oz ',
        strMeasure: '1 oz ',
        strMeasure: '1/2 oz ',
        strMeasure: '1/2 tsp ',
        strMeasure: '1 tsp ',
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure0: null,
        strMeasure1: null,
        strMeasure2: null,
        strMeasure3: null,
        strMeasure4: null,
        strMeasure5: null,
        strImageSource: null,
        strImageAttribution: null,
        strCreativeCommonsConfirmed: 'No',
        dateModified: '2017-09-02 17:57:42',
    },
    {
        idDrink: '17833',
        strDrink: 'A. J.',
        strDrinkAlternate: null,
        strTags: null,
        strVideo: null,
        strCategory: 'Ordinary Drink',
        strIBA: null,
        strAlcoholic: 'Alcoholic',
        strGlass: 'Cocktail glass',
        strInstructions:
            'Shake ingredients with ice, strain into a cocktail glass, and serve.',
        strInstructionsES: null,
        strInstructionsDE: null,
        strInstructionsFR: null,
        strInstructionsIT:
            'Shakerare gli ingredienti con ghiaccio, filtrare in una coppetta da cocktail e servire.',
        strInstructionsZHHANS: null,
        strInstructionsZHHANT: null,
        strDrinkThumb:
            'https://www.thecocktaildb.com/images/media/drink/l74qo91582480316.jpg',
        strIngredient: 'Applejack',
        strIngredient: 'Grapefruit juice',
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient0: null,
        strIngredient1: null,
        strIngredient2: null,
        strIngredient3: null,
        strIngredient4: null,
        strIngredient5: null,
        strMeasure: '1 1/2 oz ',
        strMeasure: '1 oz ',
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure0: null,
        strMeasure1: null,
        strMeasure2: null,
        strMeasure3: null,
        strMeasure4: null,
        strMeasure5: null,
        strImageSource: null,
        strImageAttribution: null,
        strCreativeCommonsConfirmed: 'Yes',
        dateModified: '2016-09-02 11:16:58',
    },
    {
        idDrink: '17187',
        strDrink: 'Derby',
        strDrinkAlternate: null,
        strTags: 'Classic,IBA',
        strVideo: 'https://www.youtube.com/watch?v=bYQTTokGkFI',
        strCategory: 'Ordinary Drink',
        strIBA: 'Unforgettables',
        strAlcoholic: 'Alcoholic',
        strGlass: 'Cocktail glass',
        strInstructions:
            'Pour all ingredients into a mixing glass with ice. Stir. Strain into a cocktail glass. Garnish with a sprig of fresh mint in the drink.',
        strInstructionsES: null,
        strInstructionsDE:
            'Alle Zutaten in ein Mischglas mit Eis geben. Rühren. In ein Cocktailglas abseihen. Mit einem Zweig frischer Minze im Getränk garnieren.',
        strInstructionsFR: null,
        strInstructionsIT:
            'Versare tutti gli ingredienti in un mixing glass con ghiaccio. Filtrare in un bicchiere da cocktail. Agitare. Guarnire con un rametto di menta fresca nella bevanda.',
        strInstructionsZHHANS: null,
        strInstructionsZHHANT: null,
        strDrinkThumb:
            'https://www.thecocktaildb.com/images/media/drink/52weey1606772672.jpg',
        strIngredient: 'gin',
        strIngredient: 'Peach Bitters',
        strIngredient: 'Mint',
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient0: null,
        strIngredient1: null,
        strIngredient2: null,
        strIngredient3: null,
        strIngredient4: null,
        strIngredient5: null,
        strMeasure: '6 cl',
        strMeasure: '2 dashes',
        strMeasure: '2 Fresh leaves',
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure0: null,
        strMeasure1: null,
        strMeasure2: null,
        strMeasure3: null,
        strMeasure4: null,
        strMeasure5: null,
        strImageSource:
            'https://commons.wikimedia.org/wiki/File:IBA_Cocktail_Derby_(28968231993).jpg',
        strImageAttribution:
            'Michael Styne https://www.flickr.com/photos/mstyne/28968231993/',
        strCreativeCommonsConfirmed: 'No',
        dateModified: '2017-09-02 11:45:56',
    },
    {
        idDrink: '12764',
        strDrink: 'Karsk',
        strDrinkAlternate: null,
        strTags: null,
        strVideo: null,
        strCategory: 'Ordinary Drink',
        strIBA: null,
        strAlcoholic: 'Alcoholic',
        strGlass: 'Highball glass',
        strInstructions:
            'Put a copper coin in a coffe-cup and fill up with coffee until you no longer see the coin, then add alcohol until you see the coin. Norwegian speciality.',
        strInstructionsES: null,
        strInstructionsDE:
            'Legen Sie eine Kupfermünze in eine Kaffeetasse und füllen Sie sie mit Kaffee, bis Sie die Münze nicht mehr sehen, dann fügen Sie Alkohol hinzu, bis Sie die Münze wieder sehen. Norwegische Spezialität.',
        strInstructionsFR: null,
        strInstructionsIT:
            "Metti una moneta di rame in una tazza da caffè e riempila di caffè finché non vedi più la moneta, quindi aggiungi l'alcol finché non vedi la moneta. Specialità norvegese.",
        strInstructionsZHHANS: null,
        strInstructionsZHHANT: null,
        strDrinkThumb:
            'https://www.thecocktaildb.com/images/media/drink/808mxk1487602471.jpg',
        strIngredient: 'Coffee',
        strIngredient: 'Grain alcohol',
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient0: null,
        strIngredient1: null,
        strIngredient2: null,
        strIngredient3: null,
        strIngredient4: null,
        strIngredient5: null,
        strMeasure: '1 part ',
        strMeasure: '2 parts ',
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure0: null,
        strMeasure1: null,
        strMeasure2: null,
        strMeasure3: null,
        strMeasure4: null,
        strMeasure5: null,
        strImageSource: null,
        strImageAttribution: null,
        strCreativeCommonsConfirmed: 'No',
        dateModified: '2017-02-20 14:54:31',
    },
    {
        idDrink: '12776',
        strDrink: 'Melya',
        strDrinkAlternate: null,
        strTags: null,
        strVideo: null,
        strCategory: 'Coffee / Tea',
        strIBA: null,
        strAlcoholic: 'Non alcoholic',
        strGlass: 'Coffee mug',
        strInstructions:
            'Brew espresso. In a coffee mug, place 1 teaspoon of unsweetened powdered cocoa, then cover a teaspoon with honey and drizzle it into the cup. Stir while the coffee brews, this is the fun part. The cocoa seems to coat the honey without mixing, so you get a dusty, sticky mass that looks as though it will never mix. Then all at once, presto! It looks like dark chocolate sauce. Pour hot espresso over the honey, stirring to dissolve. Serve with cream.',
        strInstructionsES: null,
        strInstructionsDE:
            'Espresso zubereiten. In eine Kaffeetasse 1 Teelöffel ungesüßten, pulverisierten Kakao geben, dann einen Teelöffel Honig in die Tasse träufeln. Rühren Sie um, während der Kaffee brüht, das ist der lustige Teil. Der Kakao scheint den Honig ohne Mischen zu überziehen, so dass Sie eine dichte, klebrige Masse erhalten, die aussieht, als würde sie sich nie vermischen. Dann auf einmal, presto! Es sieht aus wie dunkle Schokoladensoße. Heißen Espresso über den Honig gießen und unter Rühren auflösen. Mit Sahne servieren.',
        strInstructionsFR: null,
        strInstructionsIT:
            "Prepara l'espresso. In una tazza da caffè, mettete 1 cucchiaino di cacao amaro in polvere, quindi coprite un cucchiaino con del miele e versatelo nella tazza.",
        strInstructionsZHHANS: null,
        strInstructionsZHHANT: null,
        strDrinkThumb:
            'https://www.thecocktaildb.com/images/media/drink/xwtptq1441247579.jpg',
        strIngredient: 'Espresso',
        strIngredient: 'Honey',
        strIngredient: 'Cocoa powder',
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient0: null,
        strIngredient1: null,
        strIngredient2: null,
        strIngredient3: null,
        strIngredient4: null,
        strIngredient5: null,
        strMeasure: null,
        strMeasure: 'Unsweetened ',
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure0: null,
        strMeasure1: null,
        strMeasure2: null,
        strMeasure3: null,
        strMeasure4: null,
        strMeasure5: null,
        strImageSource: null,
        strImageAttribution: null,
        strCreativeCommonsConfirmed: 'No',
        dateModified: '2015-09-03 03:32:59',
    },
    {
        idDrink: '14598',
        strDrink: '50/50',
        strDrinkAlternate: null,
        strTags: null,
        strVideo: null,
        strCategory: 'Ordinary Drink',
        strIBA: null,
        strAlcoholic: 'Alcoholic',
        strGlass: 'Collins Glass',
        strInstructions:
            'fill glass with crushed ice. Add vodka. Add a splash of grand-marnier. Fill with o.j.',
        strInstructionsES: null,
        strInstructionsDE:
            'Glas mit zerstoßenem Eis füllen. Füge Wodka hinzu. Füge einen Spritzer Grand-Marnier hinzu. Füllen Sie mit o.j.',
        strInstructionsFR: null,
        strInstructionsIT: 'Riempire un bicchiere con ghiaccio tritato. ',
        strInstructionsZHHANS: null,
        strInstructionsZHHANT: null,
        strDrinkThumb:
            'https://www.thecocktaildb.com/images/media/drink/wwpyvr1461919316.jpg',
        strIngredient: 'Vanilla vodka',
        strIngredient: 'Grand Marnier',
        strIngredient: 'Orange juice',
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient0: null,
        strIngredient1: null,
        strIngredient2: null,
        strIngredient3: null,
        strIngredient4: null,
        strIngredient5: null,
        strMeasure: '2 1/2 oz ',
        strMeasure: '1 splash ',
        strMeasure: 'Fill with ',
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure0: null,
        strMeasure1: null,
        strMeasure2: null,
        strMeasure3: null,
        strMeasure4: null,
        strMeasure5: null,
        strImageSource: null,
        strImageAttribution: null,
        strCreativeCommonsConfirmed: 'No',
        dateModified: '2016-04-29 09:41:56',
    },
    {
        idDrink: '15328',
        strDrink: 'Zorro',
        strDrinkAlternate: null,
        strTags: null,
        strVideo: null,
        strCategory: 'Coffee / Tea',
        strIBA: null,
        strAlcoholic: 'Alcoholic',
        strGlass: 'Coffee Mug',
        strInstructions:
            'add all and pour black coffee and add whipped cream on top.',
        strInstructionsES: null,
        strInstructionsDE:
            'Alles hinzufügen, schwarzen Kaffee einfüllen und mit Schlagsahne übergießen.',
        strInstructionsFR: null,
        strInstructionsIT:
            'Aggiungere il tutto e versare il caffè nero e aggiungere sopra la panna montata.',
        strInstructionsZHHANS: null,
        strInstructionsZHHANT: null,
        strDrinkThumb:
            'https://www.thecocktaildb.com/images/media/drink/kvvd4z1485621283.jpg',
        strIngredient: 'Sambuca',
        strIngredient: 'Baileys irish cream',
        strIngredient: 'White Creme de Menthe',
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient0: null,
        strIngredient1: null,
        strIngredient2: null,
        strIngredient3: null,
        strIngredient4: null,
        strIngredient5: null,
        strMeasure: '2 cl ',
        strMeasure: '2 cl ',
        strMeasure: '2 cl ',
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure0: null,
        strMeasure1: null,
        strMeasure2: null,
        strMeasure3: null,
        strMeasure4: null,
        strMeasure5: null,
        strImageSource: null,
        strImageAttribution: null,
        strCreativeCommonsConfirmed: 'No',
        dateModified: '2017-01-28 16:34:43',
    },
    {
        idDrink: '17254',
        strDrink: 'Bijou',
        strDrinkAlternate: null,
        strTags: null,
        strVideo: null,
        strCategory: 'Cocktail',
        strIBA: null,
        strAlcoholic: 'Alcoholic',
        strGlass: 'Cocktail glass',
        strInstructions: 'Stir in mixing glass with ice and strain',
        strInstructionsES: null,
        strInstructionsDE: 'In Mischglas mit Eis verrühren und abseihen.',
        strInstructionsFR: null,
        strInstructionsIT: 'Mescolare nel mixing glass con ghiaccio e filtrare',
        strInstructionsZHHANS: null,
        strInstructionsZHHANT: null,
        strDrinkThumb:
            'https://www.thecocktaildb.com/images/media/drink/rysb3r1513706985.jpg',
        strIngredient: 'Orange Bitters',
        strIngredient: 'Green Chartreuse',
        strIngredient: 'Gin',
        strIngredient: 'Sweet Vermouth',
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient0: null,
        strIngredient1: null,
        strIngredient2: null,
        strIngredient3: null,
        strIngredient4: null,
        strIngredient5: null,
        strMeasure: '1 dash',
        strMeasure: '1 oz',
        strMeasure: '1 oz',
        strMeasure: '1 oz',
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure0: null,
        strMeasure1: null,
        strMeasure2: null,
        strMeasure3: null,
        strMeasure4: null,
        strMeasure5: null,
        strImageSource: null,
        strImageAttribution: null,
        strCreativeCommonsConfirmed: 'No',
        dateModified: '2017-12-19 18:09:45',
    },
    {
        idDrink: '17839',
        strDrink: 'Affair',
        strDrinkAlternate: null,
        strTags: null,
        strVideo: null,
        strCategory: 'Ordinary Drink',
        strIBA: null,
        strAlcoholic: 'Alcoholic',
        strGlass: 'Highball glass',
        strInstructions:
            'Pour schnapps, orange juice, and cranberry juice over ice in a highball glass. Top with club soda and serve.',
        strInstructionsES: null,
        strInstructionsDE:
            'Gießen Sie Schnaps, Orangensaft und Cranberrysaft über Eis in ein Highball-Glas. Mit Club-Soda überziehen und servieren.',
        strInstructionsFR: null,
        strInstructionsIT:
            "Versare la grappa, il succo d'arancia e il succo di mirtillo rosso sul ghiaccio in un bicchiere highball. Completare con la soda club e servire.",
        strInstructionsZHHANS: null,
        strInstructionsZHHANT: null,
        strDrinkThumb:
            'https://www.thecocktaildb.com/images/media/drink/h5za6y1582477994.jpg',
        strIngredient: 'Strawberry schnapps',
        strIngredient: 'Orange juice',
        strIngredient: 'Cranberry juice',
        strIngredient: 'Club soda',
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient0: null,
        strIngredient1: null,
        strIngredient2: null,
        strIngredient3: null,
        strIngredient4: null,
        strIngredient5: null,
        strMeasure: '2 oz ',
        strMeasure: '2 oz ',
        strMeasure: '2 oz ',
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure0: null,
        strMeasure1: null,
        strMeasure2: null,
        strMeasure3: null,
        strMeasure4: null,
        strMeasure5: null,
        strImageSource: null,
        strImageAttribution: null,
        strCreativeCommonsConfirmed: 'Yes',
        dateModified: '2016-09-01 10:05:34',
    },
    {
        idDrink: '11149',
        strDrink: 'Boxcar',
        strDrinkAlternate: null,
        strTags: null,
        strVideo: null,
        strCategory: 'Ordinary Drink',
        strIBA: null,
        strAlcoholic: 'Alcoholic',
        strGlass: 'Whiskey sour glass',
        strInstructions:
            'In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a sour glass.',
        strInstructionsES: null,
        strInstructionsDE:
            'In einem Shaker, der halb mit Eiswürfeln gefüllt ist, alle Zutaten vermengen. Gut schütteln. In ein Sour Glas abseihen.',
        strInstructionsFR: null,
        strInstructionsIT:
            'In uno shaker riempito a metà con cubetti di ghiaccio, unire tutti gli ingredienti.Filtrare in un bicchiere sour.Agitare bene.',
        strInstructionsZHHANS: null,
        strInstructionsZHHANT: null,
        strDrinkThumb:
            'https://www.thecocktaildb.com/images/media/drink/pwgtpa1504366376.jpg',
        strIngredient: 'Gin',
        strIngredient: 'Triple sec',
        strIngredient: 'Lemon juice',
        strIngredient: 'Grenadine',
        strIngredient: 'Egg white',
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient0: null,
        strIngredient1: null,
        strIngredient2: null,
        strIngredient3: null,
        strIngredient4: null,
        strIngredient5: null,
        strMeasure: '1 1/2 oz ',
        strMeasure: '1 oz ',
        strMeasure: '1 tsp ',
        strMeasure: '1/2 tsp ',
        strMeasure: '1 ',
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure0: null,
        strMeasure1: null,
        strMeasure2: null,
        strMeasure3: null,
        strMeasure4: null,
        strMeasure5: null,
        strImageSource: null,
        strImageAttribution: null,
        strCreativeCommonsConfirmed: 'No',
        dateModified: '2017-09-02 16:32:57',
    },
    {
        idDrink: '11872',
        strDrink: 'Orgasm',
        strDrinkAlternate: null,
        strTags: null,
        strVideo: null,
        strCategory: 'Ordinary Drink',
        strIBA: null,
        strAlcoholic: 'Alcoholic',
        strGlass: 'Cocktail glass',
        strInstructions:
            'Shake all ingredients with ice, strain into a chilled cocktail glass, and serve.',
        strInstructionsES: null,
        strInstructionsDE: null,
        strInstructionsFR: null,
        strInstructionsIT:
            'Shakerare tutti gli ingredienti con ghiaccio, filtrare in una coppetta da cocktail fredda e servire.',
        strInstructionsZHHANS: null,
        strInstructionsZHHANT: null,
        strDrinkThumb:
            'https://www.thecocktaildb.com/images/media/drink/vr6kle1504886114.jpg',
        strIngredient: 'Creme de Cacao',
        strIngredient: 'Amaretto',
        strIngredient: 'Triple sec',
        strIngredient: 'Vodka',
        strIngredient: 'Light cream',
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient: null,
        strIngredient0: null,
        strIngredient1: null,
        strIngredient2: null,
        strIngredient3: null,
        strIngredient4: null,
        strIngredient5: null,
        strMeasure: '1/2 oz white ',
        strMeasure: '1/2 oz ',
        strMeasure: '1/2 oz ',
        strMeasure: '1/2 oz ',
        strMeasure: '1 oz ',
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure: null,
        strMeasure0: null,
        strMeasure1: null,
        strMeasure2: null,
        strMeasure3: null,
        strMeasure4: null,
        strMeasure5: null,
        strImageSource: null,
        strImageAttribution: null,
        strCreativeCommonsConfirmed: 'No',
        dateModified: '2017-09-08 16:55:14',
    },
];
const url = 'https://www.thecocktaildb.com/api/json/v1/1/search.php?s='

const box = document.getElementById("box");
const header = document.querySelector(".header");
const main = document.querySelector(".main");
const about = document.querySelector(".about");
const information = document.getElementById("information");

header.classList.add("block")
main.classList.add("none")
about.classList.add("hidden")

function displayElements(data) {
    let html = ``
    data.map(el => {
        html += `
         <div class="card__box" id="box">
            <div class="card" id="card">
                <img src="${el.strDrinkThumb}" alt="immage" class="card__img" id="strDrinkThumb">
                <h2 class="strDrink" id="strDrink">${el.strDrink}</h2>
                <p id="strGlass" class="strGlass">${el.strGlass}</p>
                <p id="strAlcoholic" class="strAlcoholic">${el.strAlcoholic}</p>
                <button class="card__btn" onclick="buttonDelete('${el.dateModified}')" >DETAILES</button>
            </div>       
        </div>
    `
        box.innerHTML = html
    })    
}
displayElements(drinks)

function buttonDelete(dateModified) {
    let arr2 = drinks.filter(el => {
        return el.dateModified == dateModified
    });
    drinks = [...arr2];
    displayElements(drinks)
    infoCard(drinks)
    main.classList.remove("none")    
    header.classList.remove("block")    
}

function infoCard(data) {
    let html = ``
    data.map(el => {
        html = `
        <div id="information">
        <div class="main__title">
            <button class="card__btn" onclick="back()">BACK HOME</button>
            <h2 class="strDrink"> ${el.strDrink}</h2>
        </div>
        <div class="main__card">
            <img src="${el.strDrinkThumb}" alt="" class="main__img">
            <div class="main__card__title">
                <div class="card__name">
                    <p>Name:</p> <a class="card__info">${el.strDrink}</a>
                </div>
                <div class="card__name">
                    <p>Category:</p> <a class="card__info">${el.strCategory}</a>
                </div>
                <div class="card__name">
                    <p>Info:</p> <a class="card__info">${el.strAlcoholic}</a>
                </div>
                <div class="card__name">
                    <p>Glass:</p> <a class="card__info">${el.strGlass}</a>
                </div>
                <div class="card__name">
                    <p>Instructons:</p> <a class="card__info">${el.strInstructionsIT}</a>
                </div>
                <div class="card__name">
                    <p>Ingredients:</p> <a class="card__info"> ${el.strInstructionsDE}</a>
                </div>
            </div>
        </div>
    </div>
        `
        information.innerHTML = html
    })
}
infoCard(drinks)

function back() {
    location.reload();
    about.classList.add("hidden")
}
function navInfo(){
    about.classList.remove("hidden")
    main.classList.add("none")
    header.classList.remove("block")
}